language: cpp

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_USER
    - secure: "G8DS21df95TDm9NReqj5Eeh8V69qN8VF02YMfzKnq1lb13PbN5eV4sFjGK3ndaUGF+oK9rGSLo+HkNpaYdSFVEpLjFBTbYf9bjgpu012EsU4UBpMFKYEc3vGh4bqO2IWB4JKdILLBpKSC1fHaMkTuZjRXnl1uim0jajQuNNkTrUW3WcXxJ3ObN2NuYB9MMhmSXtFAU1++NnxNURChHprdkQcE/8FUnrt1L6z5EERplgOg4WjSITxYCaSOjZLhV/bav/T7x7Tci+rhO7xd0rrfHcCpmVaQzsBXNgZWEMOYIAhVcJTGMQObPtbOEYOysGQHMON9uMkT1cnagYLYCUW+mYjnbeaow3qvlI4HVThAkcpS3q2simp8BPFuH0cEa5E+s0XtUAJmSzPpX/s/6pqz2RqMMpHZ4wV+4fDbKJE1ng2up9yy3UF54aLpMjotTvd9Bl8zLtpVkld1EIVMf8KsC2QwKG++U6Z7TOFIqpLVBc8Zu6U89pv99Y1WBxgjy8JM4oeR4PrsDGDIMR4vsB38Kc5aVJs1A3QSMHRLFPLcpK1Qhy09hgTUrqElVxF2te8hLMgLoP00WWkPDYqyPl3f/HTH/ZYthkbRbcw9a8LN8IR218SbFfNQsVSxKDHLOFPu8xr6pGykw2YmYwHaXE8aZVoqdjXFUYbGxbwGVcjWHk="
    # DEPLOY_HOST
    - secure: "0L8BKnozSiwI5VMRAL6QAQ6gwVIrnBhoYq6NkACbIOchkQShZlQH9p/4/2A9/6Wu4pTrB7eTeR1JQahmjwAqUFoMfpZm+LCBZGnQpHnZd6ZgT1rcgd1MAWR4PBhoeHGbTBly00Ez9BlE5nwUxwV7XszVxbEab5tzP52JThetf+tOoL1FjUyYb3/YpPOZzlQ2gh1BeBGi8PE29i06Sa5vlGdTtJXBZmHqn2IZ2bDCNFaetI9yr6HwkxvmuhQew/vv4bsSuUidfgdZrwPodJMo0aO78INWcIl8qleHaaKvVw5sRpdk3qNPqSW517/FHMG4jDHimDnX4s2aWaq+iaVuRc4VmeQ4Ebp5Zjlf9qVuhkOCUbCy0ojrEROsqYy/oVfAH99O9lvUDBl8Q6taFJeBwhZAdDMUttqQdRSaDEspFjOk7zDoeCLN4DFzOElW1DT1XYUXUvE+WIZci5zTyhNRp6WSIKHJKHjltTqa6KscKlmWUYvroKh80SdUrjNxibM/PVl5PlFRSeXAxq3s9bC/8oNUj0CbhZBqzIP9JMbCTrjX5KnO4BPULKo94pi4LBzGtzQNs6qQ/K1srH4FsB1M9RxrD3Uqr3VcU4XbLCRLGB5rZR6Jph0IOYiRUKgQkxHnsS6mXqIizCCxDuVR6MdSvnyDcy5PuEcAEG3tC//JFnw="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build.sh

deploy:
  - provider: script
    script: .travis/deploy.sh build/artifacts/fluid-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: master
      condition: "$CC = gcc) && ($TRAVIS_PULL_REQUEST = false"
  - provider: script
    script: .travis/deploy.sh build/artifacts/fluid-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: develop
      condition: "$CC = gcc) && ($TRAVIS_PULL_REQUEST = false"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
